default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: geekbook_development
test:
  <<: *default
  database: geekbook_test

production:
  <<: *default
  database: geekbook_production
  username: geekbook
  password: <%= ENV['GEEKBOOK_DATABASE_PASSWORD'] %>
